# Generated by Django 5.1.2 on 2024-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='availability',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
