# Generated by Django 5.1.1 on 2024-11-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_alter_dashboard_user_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='accounts.user'),
        ),
    ]
