# Generated by Django 5.1.1 on 2024-11-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_customuser_alter_dashboard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='dashboard_id',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
